export const IPFS_INITIALIZING = 'IPFS_INITIALIZING';
export const IPFS_INITIALIZED = 'IPFS_INITIALIZED';
export const IPFS_FAILED = 'IPFS_FAILED';

export const IPFS_PEER_EVENT_LISTEN = 'IPFS_PEER_EVENT_LISTEN';
export const IPFS_PEER_CONNECTED = 'IPFS_PEER_CONNECTED';
export const IPFS_PEER_DISCONNECTED = 'IPFS_PEER_DISCONNECTED';
